FROM alpine:latest

RUN apk update && apk add --no-cache mysql-client gzip

COPY scripts/backup.sh /scripts/backup.sh

# No Alpine, os cronjobs do root ficam em /etc/crontabs/root
COPY scripts/cronjobs /etc/crontabs/root

RUN chmod +x /scripts/backup.sh

CMD ["crond", "-f", "-l", "2"]
