FROM nginx:latest

# Configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# 80 e 443 (HTTP e HTTPS)
EXPOSE 80 443

# O Nginx já inicia automaticamente como comando padrão da imagem base.
